version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: spotify_postgres
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  data-pipeline:
    build: .
    container_name: spotify_pipeline
    env_file:
      - .env
    depends_on:
      - postgres
    command: python -m ingestion.ingestion_listening

volumes:
  postgres_data:
